In [1]:
import torch

In [2]:
a = torch.rand(3,4)
a

tensor([[0.5910, 0.4680, 0.1091, 0.6520],
        [0.9145, 0.6528, 0.2258, 0.7579],
        [0.0117, 0.1030, 0.5603, 0.7718]])

In [3]:
c = torch.zeros(3,4, dtype=torch.long)
c

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [4]:
d = torch.tensor([[10, 20, 4],
                [0, 0, 4]])
d

tensor([[10, 20,  4],
        [ 0,  0,  4]])

In [5]:
e = torch.ones(3,4)
e

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
import numpy as np

a = np.ones(7)
b = torch.from_numpy(a)
a,b

(array([1., 1., 1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64))

In [7]:
b.numpy()

array([1., 1., 1., 1., 1., 1., 1.])

In [8]:
b *= 2
b, a

(tensor([2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64),
 array([2., 2., 2., 2., 2., 2., 2.]))

In [9]:
a = torch.rand(5, 3)
a.size(), a.dtype

(torch.Size([5, 3]), torch.float32)

In [10]:
a

tensor([[0.9082, 0.6961, 0.6806],
        [0.8827, 0.4553, 0.2097],
        [0.9176, 0.5321, 0.7273],
        [0.4830, 0.3127, 0.3144],
        [0.5673, 0.5931, 0.2044]])

In [11]:
torch.Size([3 ,6]), torch.float32

(torch.Size([3, 6]), torch.float32)

In [12]:
w = torch.rand(3,4,5)
w

tensor([[[0.2716, 0.9432, 0.4709, 0.0441, 0.2104],
         [0.1722, 0.4750, 0.8829, 0.6269, 0.3860],
         [0.7643, 0.3437, 0.8126, 0.1986, 0.4843],
         [0.8688, 0.2730, 0.2076, 0.3569, 0.5567]],

        [[0.3174, 0.7337, 0.6826, 0.9006, 0.5260],
         [0.1436, 0.5265, 0.2663, 0.4287, 0.1342],
         [0.8560, 0.9701, 0.3759, 0.5121, 0.4546],
         [0.0155, 0.6569, 0.2843, 0.2167, 0.1845]],

        [[0.6709, 0.0842, 0.6219, 0.3050, 0.8968],
         [0.7693, 0.0205, 0.9604, 0.9099, 0.1277],
         [0.0091, 0.3868, 0.1538, 0.2480, 0.5822],
         [0.3784, 0.2725, 0.8234, 0.0821, 0.4396]]])

In [13]:
a = torch.rand(5, 3)
b = a.view(3, 5)
a.shape, b.shape

(torch.Size([5, 3]), torch.Size([3, 5]))

In [14]:
a = torch.rand(5, 3)
b = a.view(3, -1)
a.shape, b.shape

(torch.Size([5, 3]), torch.Size([3, 5]))

In [15]:
a,b

(tensor([[0.0296, 0.1303, 0.5339],
         [0.1716, 0.5663, 0.4550],
         [0.6907, 0.6606, 0.8761],
         [0.1610, 0.2160, 0.9403],
         [0.2332, 0.4350, 0.2326]]),
 tensor([[0.0296, 0.1303, 0.5339, 0.1716, 0.5663],
         [0.4550, 0.6907, 0.6606, 0.8761, 0.1610],
         [0.2160, 0.9403, 0.2332, 0.4350, 0.2326]]))

In [16]:
a.data_ptr()

4632260905472

In [17]:
b.data_ptr()

4632260905472

In [18]:
a.data_ptr() == b.data_ptr()

True

In [19]:

z = torch.zeros(3, 2)
x = z.view(2, 3)
x.fill_(1)
z


tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [20]:
z = torch.zeros(3, 2)
y = z.t()
y.reshape(6)

tensor([0., 0., 0., 0., 0., 0.])

In [21]:
a = torch.arange(8).reshape(2,4)

In [22]:
a

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])

In [23]:
a.stride()

(4, 1)

In [24]:
a.view(4,2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])

In [25]:
a.view(4,2).stride()

(2, 1)

In [26]:
a.t()

tensor([[0, 4],
        [1, 5],
        [2, 6],
        [3, 7]])

In [27]:
a.t().is_contiguous()

False

In [28]:
a.t().view(1,8,1)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [29]:
a = torch.rand(4,3)
b = torch.rand(4,3)
a+b

tensor([[1.1738, 1.0565, 1.2083],
        [0.8336, 1.7912, 1.5528],
        [0.7602, 1.3264, 1.1315],
        [1.2963, 1.3740, 0.6257]])

In [30]:
torch.add(a,b)

tensor([[1.1738, 1.0565, 1.2083],
        [0.8336, 1.7912, 1.5528],
        [0.7602, 1.3264, 1.1315],
        [1.2963, 1.3740, 0.6257]])

In [31]:
result = torch.empty(4,3)
torch.add(a, b, out=result)
result

tensor([[1.1738, 1.0565, 1.2083],
        [0.8336, 1.7912, 1.5528],
        [0.7602, 1.3264, 1.1315],
        [1.2963, 1.3740, 0.6257]])

In [32]:
a = torch.rand(3,4)
b = torch.rand(4,5)
c = torch.mm(a,b)
c

tensor([[0.9437, 0.1792, 0.9334, 0.3561, 1.0485],
        [1.5729, 0.3787, 1.1469, 1.3331, 1.4756],
        [1.6193, 0.3310, 1.4131, 0.9834, 1.6512]])

In [33]:
d = torch.mul(a,b)
d

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 1

In [ ]:
a@b

In [34]:
a

tensor([[0.6878, 0.3990, 0.1226, 0.0124],
        [0.3780, 0.8598, 0.0669, 0.7063],
        [0.9789, 0.4651, 0.1149, 0.5919]])

In [35]:
a.sum(), a.min(), a.max()

(tensor(5.3836), tensor(0.0124), tensor(0.9789))

In [36]:
tensor = torch.tensor([1,2,3,4,5])
print(tensor.shape)
s = torch.sum(tensor, dim=0)
print(s)
print(s.shape)


torch.Size([5])
tensor(15)
torch.Size([])


In [37]:
tensor = torch.tensor([
    [1, 2, 3], [4, 5, 6]
])

print(tensor.shape)
print()

print("Dimension 0")
dim0= torch.sum(tensor, dim=0)
print(dim0)
print(dim0.shape)
print()


print("Dimension: 1")
dim1 = torch.sum(tensor, dim=1)
print(dim1)
print(dim1.shape)
print()


print("Dimension: -1")
dims = torch.sum(tensor, dim=-1)
print(dims)
print(dims.shape)

torch.Size([2, 3])

Dimension 0
tensor([5, 7, 9])
torch.Size([3])

Dimension: 1
tensor([ 6, 15])
torch.Size([2])

Dimension: -1
tensor([ 6, 15])
torch.Size([2])


In [38]:
dim2 = tensor.sum(tensor, dim=2)
print(dim2)
print(dim2.shape)

TypeError: sum() received an invalid combination of arguments - got (Tensor, dim=int), but expected one of:
 * (*, torch.dtype dtype = None)
      didn't match because some of the keywords were incorrect: dim
 * (tuple of ints dim, bool keepdim = False, *, torch.dtype dtype = None)
 * (tuple of names dim, bool keepdim = False, *, torch.dtype dtype = None)


In [39]:
tensor = torch.tensor([
    [[1, 2, 9], [3, 4, 0]],
    [[5, 6, 1], [7, 8, 2]]
])

print(tensor.shape)
print()

print("Dimension: 0")
dim0 = torch.sum(tensor, dim=0)
print(dim0)
print(dim0.shape)
print()

print("Dimension: 1")
dim1 = torch.sum(tensor, dim=0)
print(dim1)
print(dim1.shape)
print()

print("Dimension: 2")
dim2 = torch.sum(tensor, dim=2)
print(dim2)
print(dim2.shape)
print()

torch.Size([2, 2, 3])

Dimension: 0
tensor([[ 6,  8, 10],
        [10, 12,  2]])
torch.Size([2, 3])

Dimension: 1
tensor([[ 6,  8, 10],
        [10, 12,  2]])
torch.Size([2, 3])

Dimension: 2
tensor([[12,  7],
        [12, 17]])
torch.Size([2, 2])



In [40]:
tensor = torch.tensor([
    [
        [
            [1, 2],
            [3, 4],
            [5, 6]
        ],
        [
            [7, 8],
            [9, 10],
            [1, 2]
        ]
    ],
    [
        [
            [3, 4],
            [5, 6],
            [7, 8]
        ],
        [
            [9, 0],
            [1, 2],
            [3, 4]
        ]
    ],
    [
        [
            [5, 6],
            [7, 8],
            [9, 0]
        ],
        [
            [1, 2],
            [3, 4],
            [5, 6]
        ]
    ]
])


print(tensor.shape)
print()

print("Dimension: 0")
dim0 =  torch.sum(tensor, dim = 0)
print(dim0)
print(dim0.shape)
print()

print("Dimension: 1")
dim1 = torch.sum(tensor, dim = 1)
print(dim1)
print(dim1.shape)
print()

print("Dimension: 2")
dim2 = torch.sum(tensor, dim = 2)
print(dim2)
print(dim2.shape)
print()

print("Dimension: 3")
dim3 = torch.sum(tensor, dim=3)
print(dim3)
print(dim3.shape)
print()

print("Dimension: -1")
dims = torch.sum(tensor, dim =-1)
print(dims)
print(dims)
print(dims.shape)
print()

torch.Size([3, 2, 3, 2])

Dimension: 0
tensor([[[ 9, 12],
         [15, 18],
         [21, 14]],

        [[17, 10],
         [13, 16],
         [ 9, 12]]])
torch.Size([2, 3, 2])

Dimension: 1
tensor([[[ 8, 10],
         [12, 14],
         [ 6,  8]],

        [[12,  4],
         [ 6,  8],
         [10, 12]],

        [[ 6,  8],
         [10, 12],
         [14,  6]]])
torch.Size([3, 3, 2])

Dimension: 2
tensor([[[ 9, 12],
         [17, 20]],

        [[15, 18],
         [13,  6]],

        [[21, 14],
         [ 9, 12]]])
torch.Size([3, 2, 2])

Dimension: 3
tensor([[[ 3,  7, 11],
         [15, 19,  3]],

        [[ 7, 11, 15],
         [ 9,  3,  7]],

        [[11, 15,  9],
         [ 3,  7, 11]]])
torch.Size([3, 2, 3])

Dimension: -1
tensor([[[ 3,  7, 11],
         [15, 19,  3]],

        [[ 7, 11, 15],
         [ 9,  3,  7]],

        [[11, 15,  9],
         [ 3,  7, 11]]])
tensor([[[ 3,  7, 11],
         [15, 19,  3]],

        [[ 7, 11, 15],
         [ 9,  3,  7]],

        [[11, 15,

In [41]:
a.sum(dim=0)

tensor([2.0447, 1.7239, 0.3044, 1.3106])

In [42]:
a = torch.rand(2,2)
a[0, 0]

tensor(0.5990)

In [43]:
a[0, 0].item()

0.5990020632743835

In [44]:
a = torch.rand(4, 3)
b = torch.rand(4, 3)
c = torch.cat((a,b)) # default dimension is 0
c.shape

torch.Size([8, 3])

In [45]:
c = torch.cat((a,b), dim=1)
c.shape

torch.Size([4, 6])

In [46]:
d = torch.stack((a, b))
d.shape

torch.Size([2, 4, 3])

In [47]:
a = torch.rand(1,3,1,4)
a.shape, a.squeeze().shape

(torch.Size([1, 3, 1, 4]), torch.Size([3, 4]))

In [48]:
torch.cuda.is_available()

True

In [49]:
device_cpu = torch.device('cpu')
device_gpu = torch.device('cuda')
device_cpu, device_gpu

(device(type='cpu'), device(type='cuda'))

In [50]:
device = 'cuda' if torch.cuda.is_available else 'cpu'
device

'cuda'

In [51]:
a = torch.rand(3, 4)
a_gpu = a.to(device_gpu)
a.device, a_gpu.device

(device(type='cpu'), device(type='cuda', index=0))

In [52]:
a = torch.rand(5, 3, device=device)
a.device

device(type='cuda', index=0)

In [53]:
x = torch.tensor([[1., 2.], [3., 4.], [5., 6.]])
x.storage()

C:\Users\Prasad\AppData\Local\Temp\ipykernel_2008\273960030.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  x.storage()


 1.0
 2.0
 3.0
 4.0
 5.0
 6.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [54]:
torch.version

<module 'torch.version' from 'C:\\Users\\Prasad\\anaconda3\\Lib\\site-packages\\torch\\version.py'>

In [55]:
torch.__version__

'2.5.1+cu121'

In [56]:
a = torch.arange(10)

In [57]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
b = torch.randn(5 ,10,(5,3), dtype=torch.float64)
b

TypeError: randn(): argument 'size' failed to unpack the object at pos 3 with error "type must be tuple of ints,but got tuple"

In [59]:
b = torch.randn(5 ,10,(5,3), dtype=torch.float64)
b

TypeError: randn(): argument 'size' failed to unpack the object at pos 3 with error "type must be tuple of ints,but got tuple"

In [60]:
b = torch.empty(5, 3).uniform_(5, 10)
print(b)

tensor([[7.9868, 8.2825, 5.5395],
        [5.9572, 8.3161, 6.4732],
        [8.6184, 8.7142, 7.9803],
        [5.5546, 5.8102, 7.3378],
        [6.2752, 5.0613, 7.8713]])


In [61]:
z = torch.ones(3,3)

In [62]:
z

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [63]:
import torch

# Create a 3x3 tensor of ones with boolean dtype
b = torch.ones((3, 3), dtype=torch.bool)
print(b)


tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [64]:
# Fill a 3x3 tensor with the value True
b = torch.full((3, 3), True, dtype=torch.bool)
print(b)


tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [65]:
arr = torch.arange(10)

In [66]:
arr[1::2]

tensor([1, 3, 5, 7, 9])

In [67]:
arr[1::2]= -1

In [68]:
arr

tensor([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [69]:
arr = torch.arange(10)

In [70]:
arr.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [71]:
a = torch.arange(10).reshape(2,-1)
b = torch.ones(2,5, dtype=int)

In [72]:
a,b

(tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]),
 tensor([[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]))

In [73]:
a.shape, b.shape

(torch.Size([2, 5]), torch.Size([2, 5]))

In [74]:
result = torch.cat((a,b))
result, result.shape

(tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]),
 torch.Size([4, 5]))

In [75]:
result = torch.cat((a,b), dim=1)
result, result.shape

(tensor([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
         [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]]),
 torch.Size([2, 10]))

In [76]:
a = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b= torch.tensor([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

In [77]:
torch.where(a==b)

(tensor([1, 8]),)

In [78]:
torch.find(5,10)

AttributeError: module 'torch' has no attribute 'find'

In [ ]:
torch.where((5,10),(b))

In [79]:
b

tensor([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [80]:
tensor.where(5<=b<=10)

RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [81]:
min_val = 5
max_val = 10
mask = (b >= min_val) & (b <= max_val)

In [82]:
# elements_in_range = tensor[mask] # mistake tensor is not what we are finding b is
# mask
elements_in_range = b[mask]

In [83]:
elements_in_range

tensor([ 7, 10,  7,  9,  9,  8])

# Question: Swap columns 1 and 2 in the array arr.

arr = torch.arange(9).reshape(3,3)

In [84]:
arr = torch.arange(9).reshape(3,3)
arr

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [85]:
arr[:,1]

tensor([1, 4, 7])

In [86]:
arr[:,2]

tensor([2, 5, 8])

In [87]:
arr[:,[0,2,1]] 

tensor([[0, 2, 1],
        [3, 5, 4],
        [6, 8, 7]])

In [88]:
li = [10,20,30,40,50]

li[2],li[4] = li[4], li[2]

In [89]:
li

[10, 20, 50, 40, 30]

In [90]:
arr[:,[1,2]] = arr[:,[2,1]]

In [91]:
arr

tensor([[0, 2, 1],
        [3, 5, 4],
        [6, 8, 7]])

In [92]:
arr = arr[:,:3:1] 

In [93]:
arr

tensor([[0, 2, 1],
        [3, 5, 4],
        [6, 8, 7]])

# Question: Find the mean, median and standard deviation of 2nd column from tensor arr

arr = torch.rand(5,10)

In [94]:
arr = torch.rand(5,10)

In [95]:
arr

tensor([[0.0802, 0.4559, 0.7488, 0.3174, 0.0426, 0.5365, 0.6685, 0.8351, 0.7892,
         0.8401],
        [0.5444, 0.0893, 0.2572, 0.1286, 0.2450, 0.0108, 0.8813, 0.8416, 0.4464,
         0.8655],
        [0.8216, 0.9262, 0.2183, 0.6498, 0.4308, 0.4043, 0.2273, 0.8825, 0.1946,
         0.3346],
        [0.7120, 0.2065, 0.2394, 0.3162, 0.0320, 0.5989, 0.5307, 0.4159, 0.0842,
         0.5306],
        [0.3197, 0.1299, 0.0180, 0.3431, 0.6391, 0.4645, 0.8428, 0.0978, 0.7718,
         0.7019]])

In [96]:
arr.shape

torch.Size([5, 10])

In [97]:
arr[:,2:3:1]

tensor([[0.7488],
        [0.2572],
        [0.2183],
        [0.2394],
        [0.0180]])

In [98]:
arr[:,2:3:1].shape

torch.Size([5, 1])

In [99]:
arr[:,2:3:1].mean(), arr[:,2:3:1].median(), arr[:,2:3:1].std()

(tensor(0.2963), tensor(0.2394), tensor(0.2707))

# Question: Normalized the 2nd column such that, mean is 0 and standard deviation is 1.



In [100]:
data = arr[:,2:3:1]
data

tensor([[0.7488],
        [0.2572],
        [0.2183],
        [0.2394],
        [0.0180]])

In [101]:
def normalize(tensor):
    normalized_data = (tensor-tensor.mean()) / tensor.std()
    return normalized_data

In [102]:
result_n = normalize(data)
result_n

tensor([[ 1.6716],
        [-0.1445],
        [-0.2884],
        [-0.2104],
        [-1.0283]])

# Question: Filter the rows of arr that has 4th column > 7 and 2nd column < 7.

arr = torch.randint(5, 10, (10, 5))

In [103]:
arr = torch.randint(5,10, (10, 5))
arr

tensor([[6, 8, 9, 5, 7],
        [6, 7, 5, 8, 8],
        [5, 9, 8, 6, 6],
        [9, 5, 7, 9, 7],
        [8, 9, 6, 8, 8],
        [8, 8, 6, 7, 7],
        [7, 8, 6, 6, 5],
        [8, 7, 8, 7, 6],
        [8, 8, 5, 6, 7],
        [8, 6, 8, 8, 5]])

In [104]:
arr[:,3],  arr[:,1]

(tensor([5, 8, 6, 9, 8, 7, 6, 7, 6, 8]),
 tensor([8, 7, 9, 5, 9, 8, 8, 7, 8, 6]))

In [105]:
arr[:,3] > 7

tensor([False,  True, False,  True,  True, False, False, False, False,  True])

In [106]:
arr[:,1] < 7

tensor([False, False, False,  True, False, False, False, False, False,  True])

In [107]:
(arr[:,3] > 7) & (arr[:,1] < 7)

tensor([False, False, False,  True, False, False, False, False, False,  True])

In [108]:
arr[(arr[:,3] > 7) & (arr[:,1] < 7),:]

tensor([[9, 5, 7, 9, 7],
        [8, 6, 8, 8, 5]])

In [109]:
arr[[True,False,True,False,True,False,True,False,False,False],:]

tensor([[6, 8, 9, 5, 7],
        [5, 9, 8, 6, 6],
        [8, 9, 6, 8, 8],
        [7, 8, 6, 6, 5]])

# Question: Find the position of the largest value in the arr

arr = torch.randint(5, 10, (10,))

In [110]:
arr = torch.randint(5, 10, (10,))
arr, torch.argmax(arr)

(tensor([9, 6, 6, 7, 8, 5, 8, 9, 8, 6]), tensor(0))

In [111]:
arr = torch.randint(5,10,(10,10))
arr

tensor([[6, 8, 9, 9, 6, 7, 5, 9, 5, 5],
        [7, 7, 8, 5, 6, 9, 6, 6, 7, 6],
        [6, 8, 9, 5, 5, 8, 7, 6, 7, 7],
        [6, 6, 8, 6, 7, 5, 5, 6, 9, 6],
        [6, 9, 6, 6, 5, 8, 9, 7, 7, 5],
        [8, 7, 7, 7, 8, 7, 7, 9, 5, 6],
        [6, 5, 7, 7, 6, 5, 9, 6, 7, 9],
        [7, 5, 7, 6, 8, 9, 6, 9, 9, 5],
        [8, 8, 5, 6, 5, 8, 5, 9, 6, 9],
        [5, 9, 5, 9, 9, 9, 5, 7, 5, 7]])

In [112]:
torch.where(arr = arr.max() , arr)

SyntaxError: positional argument follows keyword argument (593651778.py, line 1)

In [113]:
torch.tensor(0)

tensor(0)

In [114]:
torch.where(arr == arr.max(), arr, torch.tensor(0))

tensor([[0, 0, 9, 9, 0, 0, 0, 9, 0, 0],
        [0, 0, 0, 0, 0, 9, 0, 0, 0, 0],
        [0, 0, 9, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 9, 0],
        [0, 9, 0, 0, 0, 0, 9, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 9, 0, 0],
        [0, 0, 0, 0, 0, 0, 9, 0, 0, 9],
        [0, 0, 0, 0, 0, 9, 0, 9, 9, 0],
        [0, 0, 0, 0, 0, 0, 0, 9, 0, 9],
        [0, 9, 0, 9, 9, 9, 0, 0, 0, 0]])

In [115]:
torch.where(arr == arr.max())

(tensor([0, 0, 0, 1, 2, 3, 4, 4, 5, 6, 6, 7, 7, 7, 8, 8, 9, 9, 9, 9]),
 tensor([2, 3, 7, 5, 2, 8, 1, 6, 7, 6, 9, 5, 7, 8, 7, 9, 1, 3, 4, 5]))

In [116]:
torch.argmax(arr)

tensor(2)

In [117]:
torch.where(arr == arr.max())

(tensor([0, 0, 0, 1, 2, 3, 4, 4, 5, 6, 6, 7, 7, 7, 8, 8, 9, 9, 9, 9]),
 tensor([2, 3, 7, 5, 2, 8, 1, 6, 7, 6, 9, 5, 7, 8, 7, 9, 1, 3, 4, 5]))

In [118]:
arr = torch.randint(5, 10, (2,10,10))
arr


tensor([[[8, 6, 9, 8, 9, 5, 7, 9, 9, 7],
         [9, 8, 8, 5, 8, 9, 7, 7, 9, 8],
         [7, 9, 6, 6, 6, 5, 8, 5, 8, 8],
         [7, 6, 6, 9, 9, 7, 8, 7, 9, 9],
         [7, 5, 7, 9, 8, 6, 9, 9, 5, 7],
         [9, 8, 6, 9, 7, 7, 5, 7, 5, 5],
         [8, 5, 9, 9, 6, 7, 7, 7, 6, 7],
         [7, 9, 7, 7, 5, 9, 7, 7, 8, 8],
         [7, 8, 7, 8, 9, 9, 9, 7, 9, 9],
         [7, 7, 9, 6, 9, 6, 8, 6, 6, 5]],

        [[8, 9, 8, 8, 6, 6, 5, 6, 9, 8],
         [5, 7, 9, 8, 6, 6, 5, 7, 5, 7],
         [6, 8, 6, 6, 5, 8, 6, 7, 6, 8],
         [7, 5, 7, 6, 5, 5, 7, 5, 6, 7],
         [7, 8, 9, 7, 6, 8, 8, 7, 7, 9],
         [6, 5, 6, 6, 8, 7, 7, 6, 9, 8],
         [5, 8, 8, 9, 8, 6, 9, 6, 7, 7],
         [6, 6, 7, 6, 5, 8, 7, 6, 6, 9],
         [8, 9, 8, 5, 8, 7, 8, 7, 5, 9],
         [6, 9, 7, 6, 9, 7, 5, 7, 7, 7]]])

In [119]:
torch.where(arr == arr.max())

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([0, 0, 0, 0, 1, 1, 1, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 8,
         8, 8, 9, 9, 0, 0, 1, 4, 4, 5, 6, 6, 7, 8, 8, 9, 9]),
 tensor([2, 4, 7, 8, 0, 5, 8, 1, 3, 4, 8, 9, 3, 6, 7, 0, 3, 2, 3, 1, 5, 4, 5, 6,
         8, 9, 2, 4, 1, 8, 2, 2, 9, 8, 3, 6, 9, 1, 9, 1, 4]))

# Question: Find the largest value in each row of arr

arr = torch.randint(5, 10, (5,10))

In [120]:
arr = torch.randint(5,10, (5,10))
arr

tensor([[5, 8, 9, 8, 5, 8, 6, 8, 9, 8],
        [6, 6, 8, 6, 8, 7, 5, 6, 8, 9],
        [5, 8, 6, 5, 7, 8, 6, 5, 6, 8],
        [7, 8, 8, 5, 9, 6, 6, 6, 8, 6],
        [6, 5, 6, 6, 8, 6, 7, 5, 6, 5]])

In [121]:
torch.where(arr == arr.max(dim=0))

TypeError: where(): argument 'condition' (position 1) must be Tensor, not bool

In [122]:
arr.max(dim=0)

torch.return_types.max(
values=tensor([7, 8, 9, 8, 9, 8, 7, 8, 9, 9]),
indices=tensor([3, 0, 0, 0, 3, 0, 4, 0, 0, 1]))

In [123]:
arr.max(dim=1)

torch.return_types.max(
values=tensor([9, 9, 8, 9, 8]),
indices=tensor([2, 9, 1, 4, 4]))

In [124]:

arr.max(dim=1).values

tensor([9, 9, 8, 9, 8])

In [125]:
arr.max(dim=0).values

tensor([7, 8, 9, 8, 9, 8, 7, 8, 9, 9])

# Find the minimum value in the arr output should be of type 'int'

arr = torch.randint(5, 10, (10,))


In [126]:

arr = torch.randint(5, 10, (10,))
arr

tensor([5, 8, 6, 9, 7, 5, 9, 9, 8, 5])

In [127]:
torch.argmin(arr)

tensor(0)

In [128]:
arr = torch.randint(5, 10, (10,10))
arr, torch.argmin(arr)


(tensor([[6, 8, 8, 9, 7, 5, 7, 8, 7, 5],
         [5, 6, 6, 5, 9, 9, 5, 7, 6, 7],
         [8, 7, 8, 5, 9, 8, 9, 6, 6, 8],
         [7, 7, 7, 7, 8, 5, 6, 6, 7, 7],
         [8, 5, 8, 9, 7, 7, 8, 9, 9, 7],
         [8, 5, 7, 6, 7, 9, 8, 9, 8, 7],
         [9, 5, 8, 8, 7, 6, 5, 7, 6, 6],
         [6, 5, 5, 7, 9, 7, 6, 6, 9, 8],
         [6, 9, 8, 9, 8, 6, 8, 7, 6, 8],
         [9, 8, 9, 9, 7, 9, 9, 6, 9, 6]]),
 tensor(5))

In [129]:
torch.argmin(arr), torch.argmin(arr, dim=1), torch.argmin(arr, dim=0)

(tensor(5),
 tensor([5, 0, 3, 5, 1, 1, 1, 1, 0, 7]),
 tensor([1, 4, 7, 1, 0, 0, 1, 2, 1, 0]))

In [130]:
arr = torch.randint(5,10, (2,5,10))
arr

tensor([[[5, 6, 9, 9, 9, 7, 5, 9, 5, 5],
         [7, 6, 5, 6, 9, 7, 6, 6, 9, 6],
         [6, 8, 8, 9, 9, 7, 6, 7, 6, 7],
         [8, 9, 8, 7, 7, 9, 8, 6, 8, 5],
         [5, 7, 6, 6, 6, 9, 8, 7, 6, 9]],

        [[6, 6, 6, 7, 8, 7, 7, 7, 7, 5],
         [7, 5, 5, 6, 5, 9, 8, 7, 6, 8],
         [6, 9, 8, 7, 9, 5, 6, 9, 9, 5],
         [8, 6, 9, 7, 6, 5, 8, 5, 7, 9],
         [5, 9, 9, 9, 9, 8, 9, 9, 8, 9]]])

In [131]:
torch.argmin(arr), torch.argmin(arr, dim=0), torch.argmin(arr, dim=1), torch.argmin(arr, dim =2)

(tensor(0),
 tensor([[0, 0, 1, 1, 1, 0, 0, 1, 0, 0],
         [0, 1, 0, 0, 1, 0, 0, 0, 1, 0],
         [0, 0, 0, 1, 0, 1, 0, 0, 0, 1],
         [0, 1, 0, 0, 1, 1, 0, 1, 1, 0],
         [0, 0, 0, 0, 0, 1, 0, 0, 0, 0]]),
 tensor([[0, 0, 1, 1, 4, 0, 0, 1, 0, 0],
         [4, 1, 1, 1, 1, 2, 2, 3, 1, 0]]),
 tensor([[0, 2, 0, 9, 0],
         [9, 1, 5, 5, 0]]))

# Get the 2nd largest values in the arr

arr = torch.randint(5, 10, (10,))

In [132]:
arr = torch.randint(5, 10, (10,))
arr1 = torch.where(arr == arr.max(),torch.tensor(0),arr)
arr,arr1

(tensor([9, 5, 9, 5, 7, 5, 5, 5, 7, 7]),
 tensor([0, 5, 0, 5, 7, 5, 5, 5, 7, 7]))

In [133]:
arr.max()

tensor(9)

In [134]:
arr1.max()

tensor(7)

In [135]:
torch.unique(arr, sorted=True)[-2]

tensor(7)

In [136]:
values, indices =  torch.topk(arr, k=2)

In [137]:
values, indices

(tensor([9, 9]), tensor([0, 2]))

In [138]:
values, indices = torch.topk(arr.flatten(),k=2 )
values[1], indices

(tensor(9), tensor([0, 2]))

In [139]:
torch.randint(5,10,(10,10)).flatten()

tensor([6, 5, 9, 7, 6, 9, 9, 7, 6, 8, 8, 6, 6, 5, 7, 6, 7, 5, 5, 5, 9, 9, 9, 7,
        5, 5, 9, 5, 7, 5, 9, 5, 8, 5, 9, 9, 9, 8, 8, 6, 8, 7, 9, 7, 5, 8, 8, 6,
        5, 9, 5, 8, 7, 6, 5, 8, 7, 6, 9, 7, 8, 5, 9, 5, 7, 8, 7, 6, 7, 6, 5, 5,
        7, 5, 7, 7, 9, 9, 7, 8, 7, 7, 9, 8, 5, 9, 8, 8, 9, 7, 6, 9, 7, 5, 6, 6,
        6, 8, 8, 7])

In [140]:
torch.randn(5, 10)

tensor([[ 0.3778,  0.0080,  0.1231,  0.3461, -1.9841,  0.0776, -0.5399,  0.6537,
          0.6024, -0.7917],
        [ 0.4063, -0.8732, -1.3543, -1.8051,  0.4215, -0.4689, -1.1259, -0.9203,
         -0.1682,  0.4724],
        [-0.2550,  2.4839, -0.7751, -0.9968, -0.5933,  0.4640,  0.5615, -0.3351,
         -0.5096,  0.1034],
        [ 1.2344, -1.3201,  3.1183, -0.5123,  0.2415, -0.4198,  0.9084,  0.2207,
          1.1686,  1.8048],
        [-0.9436, -1.0485,  0.8874, -0.3651,  0.3990,  0.2941, -0.2362, -0.7353,
         -0.0094, -0.8496]])

In [141]:
torch.randn(5,10).unique(sorted=True)

tensor([-2.0797, -2.0414, -1.9755, -1.9436, -1.7905, -1.3484, -1.3367, -1.1928,
        -1.1082, -1.0367, -0.9060, -0.8633, -0.8486, -0.7068, -0.7067, -0.6463,
        -0.5599, -0.5275, -0.4592, -0.4449, -0.3163, -0.3075, -0.2622, -0.1004,
        -0.0429,  0.0031,  0.0897,  0.1294,  0.1982,  0.2595,  0.4783,  0.5156,
         0.5407,  0.5498,  0.5899,  0.6006,  0.6251,  0.7085,  0.8511,  0.8769,
         0.9967,  1.0069,  1.1507,  1.1560,  1.1927,  1.2184,  1.3714,  1.4382,
         1.4445,  1.9094])

In [142]:
torch.randn(5,10).unique(sorted=True)[-1], torch.randn(5,10).unique(sorted=True)[-2]

(tensor(1.7717), tensor(2.1795))

####  Clip the tensor arr between 7 and 10 i.e replace all values greater than 10 to 10 and less than 7 to 7.

arr = torch.randint(5, 10, (10,))


In [143]:
arr = torch.randint(5, 10, (10,))
arr

tensor([8, 9, 6, 5, 9, 8, 5, 5, 8, 9])

In [144]:
torch.where(arr<7,7,arr)

tensor([8, 9, 7, 7, 9, 8, 7, 7, 8, 9])

In [145]:
torch.where(arr>10, 10, arr)

tensor([8, 9, 6, 5, 9, 8, 5, 5, 8, 9])

# 2nd method nested torch where as else


In [146]:
torch.where(arr<7, 7, torch.where(arr>10, 10, arr))

tensor([8, 9, 7, 7, 9, 8, 7, 7, 8, 9])

# clamp/clipped function

In [147]:
torch.clamp(arr, min=7, max=10)


tensor([8, 9, 7, 7, 9, 8, 7, 7, 8, 9])

In [148]:
arr.clamp(7,10)

tensor([8, 9, 7, 7, 9, 8, 7, 7, 8, 9])

# Combine tensors a, b & c into a single 3D tensor of shape 5x3x10.

a = torch.rand(5, 10)
b = torch.rand(5, 10)
c = torch.rand(5, 10)

In [149]:

a = torch.rand(5,10)
b = torch.rand(5,10)
c = torch.rand(5,10)

In [150]:
a,b,c

(tensor([[0.6888, 0.9662, 0.7610, 0.6057, 0.1264, 0.4641, 0.2033, 0.5480, 0.1822,
          0.9307],
         [0.6188, 0.7153, 0.3315, 0.1012, 0.0679, 0.0329, 0.1448, 0.0467, 0.4452,
          0.7331],
         [0.6473, 0.8298, 0.6726, 0.9513, 0.3447, 0.1453, 0.2124, 0.8955, 0.3433,
          0.5358],
         [0.3494, 0.8991, 0.8258, 0.3329, 0.1132, 0.2139, 0.0135, 0.2213, 0.2052,
          0.3674],
         [0.6612, 0.3879, 0.2596, 0.2393, 0.0325, 0.1243, 0.8139, 0.8411, 0.5242,
          0.2443]]),
 tensor([[0.2949, 0.6182, 0.8710, 0.2136, 0.3119, 0.5082, 0.7162, 0.4382, 0.3819,
          0.2470],
         [0.1719, 0.8749, 0.9718, 0.8105, 0.0591, 0.8542, 0.1410, 0.7525, 0.4526,
          0.6847],
         [0.9515, 0.9646, 0.2396, 0.2608, 0.3451, 0.1230, 0.9168, 0.5202, 0.2368,
          0.3227],
         [0.3555, 0.8732, 0.2592, 0.1331, 0.6700, 0.8249, 0.6706, 0.2864, 0.6530,
          0.7743],
         [0.5575, 0.2470, 0.9241, 0.2411, 0.6468, 0.8271, 0.1298, 0.5213, 0.6110,
       

In [151]:
torch.reshape(a,b,c.flatten(),(5,3,10))

TypeError: reshape() takes 2 positional arguments but 4 were given

In [152]:
a.flatten(),b.flatten(),c.flatten()

(tensor([0.6888, 0.9662, 0.7610, 0.6057, 0.1264, 0.4641, 0.2033, 0.5480, 0.1822,
         0.9307, 0.6188, 0.7153, 0.3315, 0.1012, 0.0679, 0.0329, 0.1448, 0.0467,
         0.4452, 0.7331, 0.6473, 0.8298, 0.6726, 0.9513, 0.3447, 0.1453, 0.2124,
         0.8955, 0.3433, 0.5358, 0.3494, 0.8991, 0.8258, 0.3329, 0.1132, 0.2139,
         0.0135, 0.2213, 0.2052, 0.3674, 0.6612, 0.3879, 0.2596, 0.2393, 0.0325,
         0.1243, 0.8139, 0.8411, 0.5242, 0.2443]),
 tensor([0.2949, 0.6182, 0.8710, 0.2136, 0.3119, 0.5082, 0.7162, 0.4382, 0.3819,
         0.2470, 0.1719, 0.8749, 0.9718, 0.8105, 0.0591, 0.8542, 0.1410, 0.7525,
         0.4526, 0.6847, 0.9515, 0.9646, 0.2396, 0.2608, 0.3451, 0.1230, 0.9168,
         0.5202, 0.2368, 0.3227, 0.3555, 0.8732, 0.2592, 0.1331, 0.6700, 0.8249,
         0.6706, 0.2864, 0.6530, 0.7743, 0.5575, 0.2470, 0.9241, 0.2411, 0.6468,
         0.8271, 0.1298, 0.5213, 0.6110, 0.6232]),
 tensor([0.0053, 0.9754, 0.6268, 0.7108, 0.7647, 0.0413, 0.1942, 0.5212, 0.0671,
       

In [153]:
torch.tensor(a.flatten(),b.flatten(),c.flatten())

TypeError: tensor() takes 1 positional argument but 3 were given

In [154]:
torch.reshape(a, (10,5))

tensor([[0.6888, 0.9662, 0.7610, 0.6057, 0.1264],
        [0.4641, 0.2033, 0.5480, 0.1822, 0.9307],
        [0.6188, 0.7153, 0.3315, 0.1012, 0.0679],
        [0.0329, 0.1448, 0.0467, 0.4452, 0.7331],
        [0.6473, 0.8298, 0.6726, 0.9513, 0.3447],
        [0.1453, 0.2124, 0.8955, 0.3433, 0.5358],
        [0.3494, 0.8991, 0.8258, 0.3329, 0.1132],
        [0.2139, 0.0135, 0.2213, 0.2052, 0.3674],
        [0.6612, 0.3879, 0.2596, 0.2393, 0.0325],
        [0.1243, 0.8139, 0.8411, 0.5242, 0.2443]])

In [155]:
torch.stack((torch.stack((a,b)).reshape(5,-1)),c))

SyntaxError: unmatched ')' (1422425727.py, line 1)

In [156]:
torch.stack((a,b)).reshape(5,-1)

tensor([[0.6888, 0.9662, 0.7610, 0.6057, 0.1264, 0.4641, 0.2033, 0.5480, 0.1822,
         0.9307, 0.6188, 0.7153, 0.3315, 0.1012, 0.0679, 0.0329, 0.1448, 0.0467,
         0.4452, 0.7331],
        [0.6473, 0.8298, 0.6726, 0.9513, 0.3447, 0.1453, 0.2124, 0.8955, 0.3433,
         0.5358, 0.3494, 0.8991, 0.8258, 0.3329, 0.1132, 0.2139, 0.0135, 0.2213,
         0.2052, 0.3674],
        [0.6612, 0.3879, 0.2596, 0.2393, 0.0325, 0.1243, 0.8139, 0.8411, 0.5242,
         0.2443, 0.2949, 0.6182, 0.8710, 0.2136, 0.3119, 0.5082, 0.7162, 0.4382,
         0.3819, 0.2470],
        [0.1719, 0.8749, 0.9718, 0.8105, 0.0591, 0.8542, 0.1410, 0.7525, 0.4526,
         0.6847, 0.9515, 0.9646, 0.2396, 0.2608, 0.3451, 0.1230, 0.9168, 0.5202,
         0.2368, 0.3227],
        [0.3555, 0.8732, 0.2592, 0.1331, 0.6700, 0.8249, 0.6706, 0.2864, 0.6530,
         0.7743, 0.5575, 0.2470, 0.9241, 0.2411, 0.6468, 0.8271, 0.1298, 0.5213,
         0.6110, 0.6232]])

In [157]:
torch.stack((torch.stack((a,b)).reshape(5,-1),c)).reshape(5,-1)

RuntimeError: stack expects each tensor to be equal size, but got [5, 20] at entry 0 and [5, 10] at entry 1

In [158]:
torch.cat((a,b,c))

tensor([[0.6888, 0.9662, 0.7610, 0.6057, 0.1264, 0.4641, 0.2033, 0.5480, 0.1822,
         0.9307],
        [0.6188, 0.7153, 0.3315, 0.1012, 0.0679, 0.0329, 0.1448, 0.0467, 0.4452,
         0.7331],
        [0.6473, 0.8298, 0.6726, 0.9513, 0.3447, 0.1453, 0.2124, 0.8955, 0.3433,
         0.5358],
        [0.3494, 0.8991, 0.8258, 0.3329, 0.1132, 0.2139, 0.0135, 0.2213, 0.2052,
         0.3674],
        [0.6612, 0.3879, 0.2596, 0.2393, 0.0325, 0.1243, 0.8139, 0.8411, 0.5242,
         0.2443],
        [0.2949, 0.6182, 0.8710, 0.2136, 0.3119, 0.5082, 0.7162, 0.4382, 0.3819,
         0.2470],
        [0.1719, 0.8749, 0.9718, 0.8105, 0.0591, 0.8542, 0.1410, 0.7525, 0.4526,
         0.6847],
        [0.9515, 0.9646, 0.2396, 0.2608, 0.3451, 0.1230, 0.9168, 0.5202, 0.2368,
         0.3227],
        [0.3555, 0.8732, 0.2592, 0.1331, 0.6700, 0.8249, 0.6706, 0.2864, 0.6530,
         0.7743],
        [0.5575, 0.2470, 0.9241, 0.2411, 0.6468, 0.8271, 0.1298, 0.5213, 0.6110,
         0.6232],
        [0

In [159]:
torch.cat((a,b,c)).shape

torch.Size([15, 10])

In [160]:
torch.cat((a, b, c)).reshape(5,3,10)

tensor([[[0.6888, 0.9662, 0.7610, 0.6057, 0.1264, 0.4641, 0.2033, 0.5480,
          0.1822, 0.9307],
         [0.6188, 0.7153, 0.3315, 0.1012, 0.0679, 0.0329, 0.1448, 0.0467,
          0.4452, 0.7331],
         [0.6473, 0.8298, 0.6726, 0.9513, 0.3447, 0.1453, 0.2124, 0.8955,
          0.3433, 0.5358]],

        [[0.3494, 0.8991, 0.8258, 0.3329, 0.1132, 0.2139, 0.0135, 0.2213,
          0.2052, 0.3674],
         [0.6612, 0.3879, 0.2596, 0.2393, 0.0325, 0.1243, 0.8139, 0.8411,
          0.5242, 0.2443],
         [0.2949, 0.6182, 0.8710, 0.2136, 0.3119, 0.5082, 0.7162, 0.4382,
          0.3819, 0.2470]],

        [[0.1719, 0.8749, 0.9718, 0.8105, 0.0591, 0.8542, 0.1410, 0.7525,
          0.4526, 0.6847],
         [0.9515, 0.9646, 0.2396, 0.2608, 0.3451, 0.1230, 0.9168, 0.5202,
          0.2368, 0.3227],
         [0.3555, 0.8732, 0.2592, 0.1331, 0.6700, 0.8249, 0.6706, 0.2864,
          0.6530, 0.7743]],

        [[0.5575, 0.2470, 0.9241, 0.2411, 0.6468, 0.8271, 0.1298, 0.5213,
          0

# Question: Remove all dimensions of size 1 from arr

arr = torch.rand(1, 5, 1, 10, 5, 1, 2)

In [161]:
arr = torch.rand(1, 5, 1, 10, 5, 1, 2)
arr

tensor([[[[[[[0.7687, 0.7343]],

            [[0.0981, 0.7067]],

            [[0.1702, 0.0853]],

            [[0.1734, 0.5616]],

            [[0.6354, 0.3210]]],


           [[[0.3730, 0.7780]],

            [[0.2189, 0.9432]],

            [[0.3144, 0.2460]],

            [[0.2035, 0.5055]],

            [[0.9413, 0.4595]]],


           [[[0.6089, 0.8653]],

            [[0.9292, 0.4380]],

            [[0.4533, 0.0770]],

            [[0.5042, 0.7543]],

            [[0.6083, 0.6061]]],


           [[[0.3464, 0.2093]],

            [[0.6418, 0.3096]],

            [[0.1474, 0.1834]],

            [[0.1063, 0.6677]],

            [[0.7941, 0.6007]]],


           [[[0.3733, 0.8002]],

            [[0.7491, 0.4035]],

            [[0.3724, 0.2768]],

            [[0.1477, 0.5296]],

            [[0.1723, 0.0037]]],


           [[[0.3173, 0.1350]],

            [[0.0265, 0.5898]],

            [[0.2836, 0.9607]],

            [[0.2932, 0.6619]],

            [[0.2503, 0.8079]]],


In [162]:
new_arr = arr.squeeze()

In [163]:
new_arr.shape

torch.Size([5, 10, 5, 2])

Questionnaire
What are all the things that are different in Numpy & Pytorch?

What are the rules of broadcasting?

Difference between <span class="pre">torch.stack()</span> vs <span class="pre">torch.cat()</span>

Why do we use <span class="pre">item()</span> method?

How can you calculate mean of a tensor with dtype other than float? Discuss with an example.

What does <span class="pre">squeeze()</span> method do?

Mention all the GPU related functions/methods, and how to use them?

Question: Implement the following Distance metrics using pytorch tensors

Euclidean Distance

Manhattan Distance

Minkowski Distance

Question: Implement the following Evaluation metrics using pytorch tensors

Accuracy Score

RMSE

Question: Check whether you have a CUDA enabled GPU or not, using pytorch

Question: Create a device object

Question: Create a new tensor and transfer it to the device

Question: Create a new tensor and initialize it in the device

Question: Transfer arr to GPU, without using device object

# Linear Regression

In [164]:
import torch
import numpy as np

In [165]:
inputs = np.array([[73, 67, 43],
                  [91, 88, 64],
                  [87, 134, 58],
                  [102, 43, 37],
                  [69, 96, 70]], dtype='float32')

In [166]:
inputs

array([[ 73.,  67.,  43.],
       [ 91.,  88.,  64.],
       [ 87., 134.,  58.],
       [102.,  43.,  37.],
       [ 69.,  96.,  70.]], dtype=float32)

In [167]:
targets = np.array([[56, 81, 119, 22, 103]], dtype='float32')
targets.reshape((-1, 1))

array([[ 56.],
       [ 81.],
       [119.],
       [ 22.],
       [103.]], dtype=float32)

In [168]:
targets.shape

(1, 5)

In [169]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

inputs[0], targets

(tensor([73., 67., 43.]), tensor([[ 56.,  81., 119.,  22., 103.]]))

In [170]:
w = torch.randn(1,3, requires_grad=True)
b = torch.randn(1, requires_grad= True)

w,b

(tensor([[1.9594, 0.9820, 0.4264]], requires_grad=True),
 tensor([0.6246], requires_grad=True))

In [171]:
def model(x):
    return x @ w.t() + b

In [172]:
preds = model(inputs)
preds

tensor([[227.7847],
        [292.6286],
        [327.4036],
        [258.4806],
        [259.9366]], grad_fn=<AddBackward0>)

In [173]:
import torch.nn as nn

In [174]:
loss_fn = nn.MSELoss() # Initialize loss function
loss = loss_fn(preds, targets)
loss

C:\Users\Prasad\anaconda3\Lib\site-packages\torch\nn\modules\loss.py:608: UserWarning: Using a target size (torch.Size([1, 5])) that is different to the input size (torch.Size([5, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


tensor(41165.3320, grad_fn=<MseLossBackward0>)

In [175]:
loss.backward()
w.grad

tensor([[33554.3359, 35335.9805, 21818.1289]])

In [176]:
lr = 1e-5
with torch.no_grad():
    w -= w.grad * lr
    b -= b.grad * lr

In [177]:
with torch.no_grad():
    w.grad.zero_()
    b.grad.zero_()

In [178]:
preds = model(inputs)
loss = loss_fn(preds, targets)
print(loss)

tensor(17763.2383, grad_fn=<MseLossBackward0>)


In [179]:
def mse(y_pred, y_true):
    error = y_pred - y_true
    return torch.mean(error**2)

In [180]:
lr = 1e-5
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad(): # we use no gradient for weight updation
        w -= w.grad * lr
        b -= b.grad * lr
        w.grad.zero_()
        b.grad.zero_()

In [181]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(1270.8129, grad_fn=<MeanBackward0>)


In [182]:
preds

tensor([[64.8780],
        [80.7458],
        [83.8253],
        [85.1135],
        [64.0010]], grad_fn=<AddBackward0>)

In [183]:
targets

tensor([[ 56.,  81., 119.,  22., 103.]])

In [184]:
    from torch import nn

In [185]:
inputs = np.array([[73, 67, 43],
                  [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],
                 dtype='float32')

targets = np.array([[56, 81, 119, 22, 103, 57, 80, 118, 21, 104, 57, 82, 119, 20, 102]], dtype='float32').reshape(-1,1)

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [186]:
targets

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.],
        [ 57.],
        [ 80.],
        [118.],
        [ 21.],
        [104.],
        [ 57.],
        [ 82.],
        [119.],
        [ 20.],
        [102.]])

In [187]:
from torch.utils.data import TensorDataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.],
         [ 81.],
         [119.]]))

In [188]:
from torch.utils.data import DataLoader

bs = 5
train_loader = DataLoader(train_ds, batch_size = bs, shuffle = True)

for xb, yb in train_loader:
    print(xb)
    print(yb)
    break

tensor([[ 69.,  96.,  70.],
        [ 87., 135.,  57.],
        [ 91.,  87.,  65.],
        [ 87., 134.,  58.],
        [ 73.,  67.,  43.]])
tensor([[103.],
        [119.],
        [ 80.],
        [119.],
        [ 56.]])


What this means
You are creating a custom neural network
It inherits from nn.Module
This makes it:
trainable
compatible with autograd
compatible with optimizers
compatible with GPU/CPU switching
📌 All PyTorch models must inherit from nn.Module



2️⃣ __init__ — Model construction
def __init__(self, input_dim, output_dim):


input_dim → number of input features

output_dim → number of outputs (targets)

Example:

input_dim = 3
output_dim = 1

🔹 super(Linear_Regression, self).__init__()

This:

Initializes the parent class (nn.Module)

Registers your model properly with PyTorch

Enables:

.parameters()

.to(device)

.train() / .eval()

❌ Without this → model won’t train correctly.

3️⃣ self.linear = torch.nn.Linear(input_dim, output_dim)

This is the entire linear regression model.

Internally, PyTorch creates:

weight: shape (output_dim, input_dim)

bias: shape (output_dim)

Mathematically:

𝑦
=
𝑥
𝑊
𝑇
+
𝑏
y=xW
T
+b

This replaces your manual code:

w = torch.randn(...)
b = torch.randn(...)


And both automatically have:

requires_grad = True

4️⃣ forward(self, x) — Forward pass
def forward(self, x):


This defines how data flows through the model.

PyTorch calls this automatically when you do:

model(x)


You NEVER call forward() directly.

🔹 outputs = self.linear(x)

This applies:

outputs
=
𝑥
𝑊
𝑇
+
𝑏
outputs=xW
T
+b

x: shape (batch_size, input_dim)

outputs: shape (batch_size, output_dim)

Autograd tracks everything here automatically.

🔹 return outputs

Returns predictions.

In [189]:
class Linear_Regression(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        super(Linear_Regression, self).__init__()
        self.linear = torch.nn.Linear(input_dim, output_dim)
    def forward(self, x):
        outputs = self.linear(x)
        return outputs

In [190]:
model = Linear_Regression(3,1)
list(model.parameters())

[Parameter containing:
 tensor([[0.3815, 0.2454, 0.1966]], requires_grad=True),
 Parameter containing:
 tensor([0.1262], requires_grad=True)]

In [191]:
preds = model(inputs)
preds

tensor([[52.8751],
        [69.0253],
        [77.6073],
        [56.8708],
        [63.7742],
        [53.0113],
        [68.9765],
        [78.1855],
        [56.7346],
        [63.5893],
        [52.8263],
        [69.1615],
        [77.6561],
        [57.0557],
        [63.6380]], grad_fn=<AddmmBackward0>)

In [192]:
import torch.nn.functional as F

loss_fn = F.mse_loss
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(932.6732, grad_fn=<MseLossBackward0>)


In [193]:
opt = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [194]:
# utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            pred = model(xb)
            loss = loss_fn(pred, yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [195]:
fit(100, model, loss_fn, opt, train_loader)

Epoch [10/100], Loss: 614.8488
Epoch [20/100], Loss: 190.9637
Epoch [30/100], Loss: 62.4361
Epoch [40/100], Loss: 44.5417
Epoch [50/100], Loss: 28.3374
Epoch [60/100], Loss: 11.8775
Epoch [70/100], Loss: 14.1108
Epoch [80/100], Loss: 6.9191
Epoch [90/100], Loss: 6.7248
Epoch [100/100], Loss: 6.4826


In [196]:
preds = model(inputs)
preds

tensor([[ 57.2564],
        [ 80.5386],
        [120.9318],
        [ 22.4376],
        [ 98.3528],
        [ 56.0001],
        [ 80.1176],
        [121.0791],
        [ 23.6939],
        [ 99.1881],
        [ 56.8354],
        [ 79.2823],
        [121.3529],
        [ 21.6023],
        [ 99.6091]], grad_fn=<AddmmBackward0>)

In [197]:
targets

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.],
        [ 57.],
        [ 80.],
        [118.],
        [ 21.],
        [104.],
        [ 57.],
        [ 82.],
        [119.],
        [ 20.],
        [102.]])

In [198]:
model(torch.tensor([[75, 63, 44.]]))

tensor([[53.4105]], grad_fn=<AddmmBackward0>)

# Questionnaire
1. What is the mathematical equation of a simple linear regression model, and what do its components represent?

2. In PyTorch, how do you initialize the weights and bias manually for a linear regression model without using torch.nn.Linear?

3.Why is the Mean Squared Error (MSE) commonly used as the loss function in linear regression, and how can it be implemented using PyTorch?

4. Explain the role of the gradient descent algorithm in training a linear regression model. 

5. What are the key steps involved in training a linear regression model in PyTorch from scratch?

6. After training a linear regression model, how do you evaluate its performance? Mention at least two metrics that can be used.



# Gradient Calculation with Autograd

In [ ]:
import torch

In [ ]:
x = torch.randn(3)
print(x)

In [ ]:
# now we want to calculate gradients of some functions with respect to x we do
x = torch.randn(3, requires_grad=True )
print(x)

y= x+2 
print(y)    # AddBackward0

z = y*y*2
print(z)    # MulBackward

k = y*y*2
k = k.mean()
print(k)     # MeanBackward0

k.backward() # dk/dx
print(x.grad)

In [ ]:
# now if we dont use requires_grad=True we will get error

c = torch.randn(3, requires_grad=False) # default value is false
print(c)

q = c+2
print(q)

r = q*q*2
# r = r.mean()
print(r)

r.backward()
print(c.grad)


In [ ]:
c = torch.randn(3, requires_grad= True) # default value is false
print(c)

q = c+2
print(q)

r = q*q*2
# r = r.mean() # scalar value
print(r)


v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32) # if no scalar then we have to give it a vector
r.backward(v) #dr/dc
print(c.grad)

In [ ]:
x = torch.randn(3, requires_grad=True)
print(x)


# WHEN we dont need gradient calculation
# when we have trailing "_" in pytorch then it will modify our variable inplace

# x.requires_grad_(False)
# x.detach()
# with torch.no_grad():

In [ ]:
x.requires_grad_(False)
print(x)

# we see the requires_grad=True is gone i.e it is False

In [ ]:
y = x.detach()
print(y)

# here we see y has the same value but doesnt require gradient

In [ ]:
with torch.no_grad():
    y = x + 2
    print(y)

# so we dont have gradient function output

In [ ]:
weights = torch.ones(4, requires_grad = True)

for epoch in range(3):
    model_output = (weights*3).sum()

    model_output.backward()

    print(weights.grad)



In [ ]:
weights = torch.ones(4, requires_grad = True)

for epoch in range(3):
    model_output = (weights*3).sum()

    model_output.backward()

    print(weights.grad)

    weights.grad.zero_()

# the gradients are stored in the .grad function

# EXERCISE LINEAR REGRESSION

In [ ]:
import torch


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv(r"D:\data_ml_dl\data_dl\Advertising.csv")

In [ ]:
df

In [ ]:
df=df.drop(columns="Unnamed: 0")

In [ ]:
df

In [ ]:
inputs = df.iloc[:,0:3]
targets = df.iloc[:,3].values

In [ ]:
inputs

In [ ]:
targets

In [ ]:
targets.reshape((-1, 1))

In [ ]:
targets.shape

In [ ]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

inputs[0], targets

In [ ]:
inputs = np.array(inputs, dtype=np.float32)


In [ ]:
targets = np.array(targets, dtype=np.float32)

In [ ]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

inputs[0], targets

In [ ]:
from torch.utils.data import TensorDataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

In [ ]:
from torch.utils.data import DataLoader

bs=5
train_loader = DataLoader(train_ds, batch_size=bs, shuffle=True)


for xb, yb in train_loader:
    print(xb)
    print(yb)
    break

In [ ]:
import torch.nn


In [ ]:
class Linear_Regression(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        super(Linear_Regression, self).__init__()
        self.linear = torch.nn.Linear(input_dim, output_dim)
    def forward(self, x):
        outputs = self.linear(x)
        return outputs

In [ ]:
model = Linear_Regression(3,1)
list(model.parameters())

In [ ]:
preds = model(inputs)
preds

In [ ]:
import torch.nn.functional as F

loss_fn = F.mse_loss
loss = loss_fn(model(xb).squeeze(dim=1), yb)
print(loss)

In [ ]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [ ]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            pred = model(xb)
            loss= loss_fn(pred.squeeze(dim=1), yb)
            loss.backward() # compute gradient
            opt.step() # update parameters using gradients
            opt.zero_grad() # reset the gradient to zero
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))
            

In [ ]:
fit(100, model, loss_fn, opt, train_loader)

In [ ]:
preds[:5], targets[:5]

In [ ]:
model(torch.tensor([[44.5	,39.3	,45.1]]))